CREATE TABLE users(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER'
        CHECK(role IN('USER','ADVISOR','ADMIN')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP    
);